use_frameworks!

platform :ios, '10.0'

target 'FZClosureScrollView_Example' do
  pod 'FZClosureScrollView', :path => '../'

  target 'FZClosureScrollView_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
